import { initializeApp } from 'firebase/app';
import { getFirestore, collection, addDoc, getDocs, updateDoc, deleteDoc, doc, query, onSnapshot, setDoc } from 'firebase/firestore';

const firebaseConfig = {
  apiKey: "AIzaSyB-Vm_fcJxb06GQ9a0QTX5LTW2o8JJdMXQ",
  authDomain: "majestic-mission-wh7sp.firebaseapp.com",
  projectId: "majestic-mission-wh7sp",
  storageBucket: "majestic-mission-wh7sp.firebasestorage.app",
  messagingSenderId: "887435040134",
  appId: "1:887435040134:web:445823f2d21c93a1980807",
  measurementId: ""
};

const app = initializeApp(firebaseConfig);

// Initialize Firestore specifying the databaseId generated by AI Studio
export const db = getFirestore(app, "ai-studio-dealermanagement-28b906f6-ad4c-4671-9db2-d50a4c81d966");

// Export collections for easy use
export const usersCollection = collection(db, 'users');
export const transactionsCollection = collection(db, 'transactions');
